// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzoiufmwejmnnpsmpqsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6b2l1Zm13ZWptbm5wc21wcXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NzA1NjQsImV4cCI6MjA2NDE0NjU2NH0.Nl0da2voU1mJujcgojr5MkcGSxvkb7AgwSGxKZo9bv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);